export const SET_COUNTRY_LIST = "SET_COUNTRY_LIST";
export const SELECT_LOCATION = "SELECT_LOCATION";
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const MODIFY_LOCATION = 'MODIFY_LOCATION';